train_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/train_data_dir/training.csv"
validation_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/validation_data_dir/validation.csv"
test_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/test_data_dir/testing.csv"

batch_size: 64
learning_rate: 0.0003
num_epochs: 30

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 200, 1]

model: "cnn"

segment_length: 5  # number of seconds each spectrogram represents
pixel_per_second: 40

label_names: ["EN", "IT", "SA", "SP"]
num_classes: 4