train_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/train_data_dir/training.csv"
validation_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/validation_data_dir/validation.csv"
test_data_dir: "C:/Users/fraca/Documents/GitHub/crnn_lid/test_data_dir/testing.csv"

batch_size: 64
learning_rate: 0.001
num_epochs: 40

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
input_shape: [129, 200, 1]

model: "resnet"

segment_length: 10  # number of seconds each spectogram represents
pixel_per_second: 50

label_names: ["EN", "IT", "SP", "SR"]
num_classes: 4